import type { StartPageConfig, WorkspaceSettings } from '../types'

export const DEFAULT_SECTIONS: StartPageConfig['sections'] = {
  showSearch: true,
  showQuickLinks: true,
  showSchedule: true,
  showHandover: true,
  showInfoCards: true,
  showShiftPulse: true,
  showWeather: true,
}

export const DEFAULT_WINDOWS_SHORTCUTS: WorkspaceSettings['windowsShortcuts'] = [
  {
    id: 'calc',
    label: 'Kalkulator',
    icon: '🔢',
    description: 'Kalkulator Windows',
    target: 'calculator:',
    targetType: 'protocol',
    enabled: true,
  },
  {
    id: 'explorer',
    label: 'Pliki',
    icon: '📁',
    description: 'Eksplorator plików',
    target: 'file:///C:/',
    targetType: 'protocol',
    enabled: true,
  },
  {
    id: 'notepad',
    label: 'Notatnik',
    icon: '📝',
    description: 'Notatnik Windows — uruchom z menu Start jeśli skrót nie działa w Chrome',
    target: 'notepad',
    targetType: 'info',
    enabled: false,
  },
]

export const DEFAULT_WORKSPACE: WorkspaceSettings = {
  forceFullscreen: false,
  lockFullscreen: true,
  defaultLinkOpenMode: 'shell',
  panelUrl: '',
  windowsShortcuts: DEFAULT_WINDOWS_SHORTCUTS,
  barPosition: 'top',
  barHeight: 52,
}

export const DEFAULT_CONFIG: StartPageConfig = {
  version: 1,
  companyName: 'Biała Restauracja',
  tagline: 'Ekran główny lokalu',
  adminPin: '2024',
  searchEngine: 'google',
  weather: { city: 'Białystok', latitude: null, longitude: null },
  sections: DEFAULT_SECTIONS,
  workspace: DEFAULT_WORKSPACE,
  quickLinks: [
    {
      id: 'pos',
      label: 'POS',
      url: 'https://pos.example.com',
      iconMode: 'auto',
      openMode: 'shell',
      embedSize: 'medium',
      icon: '🧾',
      color: '#10b981',
      pinned: true,
    },
    {
      id: 'mail',
      label: 'Poczta',
      url: 'https://mail.google.com',
      iconMode: 'auto',
      openMode: 'shell',
      embedSize: 'medium',
      icon: '📧',
      color: '#3b82f6',
      pinned: true,
    },
    {
      id: 'facebook',
      label: 'Facebook',
      url: 'https://www.facebook.com',
      iconMode: 'auto',
      openMode: 'shell',
      embedSize: 'medium',
      icon: '📘',
      color: '#1877f2',
      pinned: true,
    },
    {
      id: 'magazyn',
      label: 'Magazyn',
      url: 'https://damianmalenta.github.io/magazyn_biala/',
      iconMode: 'auto',
      openMode: 'shell',
      embedSize: 'medium',
      icon: '🏭',
      color: '#f59e0b',
      pinned: true,
    },
    {
      id: 'smartlunch',
      label: 'SmartLunch',
      url: 'https://smartlunch.pl',
      iconMode: 'auto',
      openMode: 'shell',
      embedSize: 'medium',
      icon: '🍽️',
      color: '#ec4899',
      pinned: true,
    },
    {
      id: 'muzyka',
      label: 'Muzyka',
      url: 'music://player',
      linkType: 'music',
      iconMode: 'manual',
      openMode: 'embed',
      embedSize: 'medium',
      icon: '🎵',
      color: '#a855f7',
      pinned: true,
    },
  ],
  infoCards: [
    {
      id: 'wifi',
      title: 'Wi-Fi gościnne',
      content: 'Sieć: Restauracja_Gosc\nHasło: zapytaj kierownika',
      icon: '📶',
      pinned: true,
    },
    {
      id: 'alarm',
      title: 'Alarm / zamknięcie',
      content: '1. Wyłącz piec i frytkownicę\n2. Sprawdź drzwi tylne\n3. Włącz alarm — kod w notesie kierownika',
      icon: '🔐',
      pinned: true,
    },
    {
      id: 'kontakt',
      title: 'Kontakt awaryjny',
      content: 'Kierownik: +48 500 000 000\nSerwis POS: +48 600 000 000',
      icon: '📞',
      pinned: true,
    },
  ],
  employees: [
    { id: 'e1', name: 'Anna', color: '#10b981', role: 'Kuchnia' },
    { id: 'e2', name: 'Piotr', color: '#3b82f6', role: 'Sala' },
    { id: 'e3', name: 'Kasia', color: '#f59e0b', role: 'Bar' },
    { id: 'e4', name: 'Marek', color: '#ec4899', role: 'Magazyn' },
  ],
  schedule: {
    pon: [
      { employeeId: 'e1', start: '08:00', end: '16:00' },
      { employeeId: 'e2', start: '10:00', end: '18:00' },
      { employeeId: 'e4', start: '07:00', end: '15:00' },
    ],
    wt: [
      { employeeId: 'e3', start: '12:00', end: '20:00' },
      { employeeId: 'e2', start: '10:00', end: '18:00' },
    ],
    sr: [
      { employeeId: 'e1', start: '08:00', end: '16:00' },
      { employeeId: 'e4', start: '07:00', end: '15:00' },
    ],
    czw: [
      { employeeId: 'e3', start: '12:00', end: '20:00' },
      { employeeId: 'e2', start: '10:00', end: '18:00' },
    ],
    pt: [
      { employeeId: 'e1', start: '08:00', end: '16:00' },
      { employeeId: 'e2', start: '10:00', end: '22:00' },
      { employeeId: 'e3', start: '14:00', end: '22:00' },
    ],
    sob: [
      { employeeId: 'e2', start: '10:00', end: '22:00' },
      { employeeId: 'e3', start: '12:00', end: '22:00' },
    ],
    nd: [],
  },
  handoverNotes: [
    {
      id: 'h1',
      author: 'System',
      content: 'Tu wpisuj ważne info między zmianami — np. brakujące produkty, rezerwacje VIP, usterki sprzętu.',
      createdAt: new Date().toISOString(),
      pinned: true,
      done: false,
      mentions: [],
    },
  ],
}
